# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Riodan

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install 
    npm run build --force
  displayName: 'npm install and build'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (c2db819e-a9e5-486a-a182-6621e1783cf6)'
    appType: 'webAppLinux'
    appName: 'ReactApp-ADO'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
