apiVersion: app/v1
kind: Deployment
metadata:
  name: react-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-ado
  template:
    metadata:
      labels:
        app: react-ado
    spec:
      containers:
        - name: react-front-end
          image: -----------------
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-app-front-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    app: react-ado
