apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: real-estate-for-all
  template:
    metadata:
      labels:
        app: real-estate-for-all
    spec:
      containers:
        - name: real-estate-for-all
          image: fouadallaoui/reactapp-docker-k8s:$(Build.BuildId)
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: real-estate-for-all
spec:
  selector:
    app: real-estate-for-all
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
